name: final_schaf
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scanpy
  - anndata
  - pytorch
  - torchvision
  - torchtext
  - pytorch-cuda=12.1
  - scikit-learn
  - tqdm
  - matplotlib
  - seaborn
  - pillow
  - imageio
  - opencv
  - numba
  - scipy
  - pip
  - pip:
      - wandb
      - tangram-sc
      - scgpt
      - timm
      - einops
      - ipython